name: Generate memory usage report
description: Generate a memory usage report for a specific branch

inputs:
  branch:
    required: true

outputs:
  report:
    description: "A raw memory usage report"
    value: ${{ steps.make_report.outputs.report }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        ref: ${{ inputs.branch }}
    - name: Report
      id: make_report
      shell: bash
      run: |
        make test
        echo "report=$(cat build/test/unit/*.size)" >> $GITHUB_OUTPUT
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Memory-report-${{ inputs.branch }}
        path: build/memory-report-${{ inputs.branch }}.txt
