name: Continuous Integration

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install deps
        run: sudo apt-get install lcov
      - name: Run tests
        run: |
          cmake -Bbuild && cd build
          cmake --build .
          make test
      - name: Upload coverage artifact
        uses: actions/upload-artifact@master
        with:
          name: lcov-info-pr
          path: build/coverage.total
        if:  ${{ github.event_name == 'pull_request' }}
  coverage:
    needs: ci
    uses: ./.github/workflows/coverage.yml
    if:  ${{ github.event_name == 'pull_request' }}
