name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install deps
        run: sudo apt-get install lcov
      - name: Run tests
        run: |
          cmake -Bbuild && cd build
          cmake --build .
          make test
  coverage:
    uses: ./.github/workflows/coverage.yml
    if:  ${{ github.event_name == 'pull_request' }}