name: Continuous Integration

on:
  push:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install deps
        run: sudo apt-get install lcov
      - name: Run tests
        run: |
          cmake -Bbuild && cd build
          cmake --build .
          make test
      - name: Coverage
        uses: romeovs/lcov-reporter-action@2a28ec3e25fb7eae9cb537e9141603486f810d1a
        with:
          lcov-base: build/coverage.total
          lcov-file: build_pr/coverage.total
          delete-old-comments: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if:  ${{ github.event_name == 'pull_request' }}