name: Continuous Integration

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install deps
        run: sudo apt-get install lcov
      - name: Run tests
        run: |
          cmake -Bbuild && cd build
          cmake --build .
          make test
      - name: Run tests on main for coverage comparison
        run: |
          git checkout main
          cmake -Bbuild-old && cd build-old
          cmake --build .
          make test
        if:  ${{ github.event_name == 'pull_request' }}
      - name: Coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: build/coverage.info
          lcov-base: build-old/coverage.info
          delete-old-comments: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if:  ${{ github.event_name == 'pull_request' }}