name: Continuous Integration

on: [push, pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
            submodules: recursive
      - name: Install deps
        run: sudo apt-get install lcov
      - name: Run tests
        run: |
          cmake -Bbuild && cd build
          cmake --build .
          make test
      - name: Coverage
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: build/coverage.info
          github-token: ${{ secrets.GITHUB_TOKEN }}
      if:  ${{ github.event_name == 'pull_request' }}